name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      filename:
        description: 'HTML file to deploy (default: simple_pwa_app.html)'
        required: false
        default: 'simple_pwa_app.html'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set filename
      id: filename
      run: |
        if [ "${{ github.event.inputs.filename }}" != "" ]; then
          echo "filename=${{ github.event.inputs.filename }}" >> $GITHUB_OUTPUT
        else
          echo "filename=simple_pwa_app.html" >> $GITHUB_OUTPUT
        fi

    - name: Validate file exists
      run: |
        if [ ! -f "${{ steps.filename.outputs.filename }}" ]; then
          echo "Error: File ${{ steps.filename.outputs.filename }} not found!"
          exit 1
        fi
        echo "Found file: ${{ steps.filename.outputs.filename }}"

    - name: Prepare for deployment
      run: |
        # Create index.html from the specified file
        cp "${{ steps.filename.outputs.filename }}" index.html
        echo "Deploying ${{ steps.filename.outputs.filename }} as index.html"

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: .

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

    - name: Output deployment info
      run: |
        echo "✅ Successfully deployed ${{ steps.filename.outputs.filename }} to GitHub Pages"
        echo "🌐 Your app will be available at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
        echo "📁 Deployed file: index.html (copied from ${{ steps.filename.outputs.filename }})"